### PR TITLE
Fixed a little issue with spanish translation

### PR DESCRIPTION
**Pull request by BanCrash**
Hello again! I encontered a little issue when translating the skin. In spanish, "none" could be translated as "ninguno" or "ninguna" regarding the genre of the word (For example, in animation settings would be translated as "Ninguna", and in "process" would be translated as "Ninguno"). I made two different ways of solve this issue:

- In solution 1, ([Language1 branch on my repository](https://github.com/BanCrash/Lauhdutin/tree/Language1)) I changed "button_label_none" to "button_label_none_masc" (masculine) and "button_label_none_fem" (femenine). This solution solve the issue in Spanish and only adds one more line on translation file. However, could make troubles with other languages.

- In solution 2 (this PR), I created "button_label_none_animation", "button_label_none_process", "button_label_none_notes", "button_label_none_tags" and "button_label_none_bangs". This solution probably would work for much languages, however added 4 more lines that are unnecesary on English language.

About solution 2, I renamed the strings as suffixes to have all "nones" together. However, if you think it's better to keep consistency I could rename them to their proper name and placed on their right place (for example "setting_animation_label_none").

### CODE REVIEW

**Comment by BanCrash** [comment]
Perfect! I made the changes to adjust to that.

**Comment by BanCrash** [comment]
By the way, when the final version is released, the way I'll have to proceed is to make a PR to development-v3 branch with Spanish language placed inside translation folder? Or somehow else?

**Comment by Kapiainen** [comment]
> By the way, when the final version is released, the way I'll have to proceed is to make a PR to development-v3 branch with Spanish language placed inside translation folder?

That is the current plan. The English translation file is the only one that I can guarantee will be up-to-date whenever a new version is released and will be the only one bundled in the release archives. Other languages will then be added to each release as separate  downloads once they are up-to-date. Each version of Lauhdutin may not even require any changes to the translations and some of those changes (e.g. if the key of a translation is renamed from `button_label_bangs_none` to `bangs_label_none`) can be handled by the migration system that is included in the localization system.

**Comment by BanCrash** [comment]
Perfect! All clear then, thanks for the answer!

**Pull request merged**
